#!/usr/bin/env python3
"""Generate tiny blur placeholders for every product image.

Without a placeholder, Next.js renders a lazy-loaded product image as raw alt
text inside an empty box until the optimized variant arrives. On a 46 card grid
that reads as a page full of broken images. A blurDataURL means the shopper sees
a blurred preview of the actual product immediately, then a sharp swap.

Each placeholder is a 12x12 WEBP encoded as a data URI, roughly 200 bytes.

Usage:  python3 scripts/generate-image-blur.py src/data/image-blur.ts
"""

from __future__ import annotations

import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS = ROOT / "public" / "products"
BLUR_SIZE = 12


def blur_data_uri(path: Path) -> str:
    with Image.open(path) as im:
        im = im.convert("RGB")
        im = im.resize((BLUR_SIZE, BLUR_SIZE), Image.LANCZOS)
        im = im.filter(ImageFilter.GaussianBlur(radius=0.6))
        buf = io.BytesIO()
        im.save(buf, "WEBP", quality=60, method=6)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    return f"data:image/webp;base64,{encoded}"


def main(out_path: str) -> int:
    entries: list[tuple[str, str]] = []

    for folder in sorted(p for p in PRODUCTS.iterdir() if p.is_dir()):
        for name in ("main.webp", "detail.webp"):
            image = folder / name
            if image.exists():
                key = f"/products/{folder.name}/{name}"
                entries.append((key, blur_data_uri(image)))

    lines = [
        "/**",
        " * Blur placeholders for product photography.",
        " *",
        " * Generated by scripts/generate-image-blur.py. Do not edit by hand.",
        " *",
        " * Next.js lazy-loads product images and generates each optimized size on",
        " * demand. Without a placeholder the browser paints raw alt text in an empty",
        " * box until the image arrives, which on a full catalog grid looks like every",
        " * image is broken. These data URIs give an immediate blurred preview.",
        " */",
        "export const imageBlurDataUrls: Record<string, string> = {",
    ]
    for key, uri in entries:
        lines.append(f"  '{key}':")
        lines.append(f"    '{uri}',")
    lines.append("};")
    lines.append("")
    lines.append("/** Blur placeholder for an image path, if one was generated. */")
    lines.append("export function getBlurDataUrl(src: string): string | undefined {")
    lines.append("  return imageBlurDataUrls[src];")
    lines.append("}")
    lines.append("")

    Path(out_path).write_text("\n".join(lines))
    print(f"wrote {out_path}: {len(entries)} blur placeholders")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
